# Generated by Django 4.2.2 on 2023-07-01 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_alter_car_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='city',
            field=models.CharField(default='', max_length=100),
        ),
    ]
